#!/bin/bash

if [ -z "$1" ]; then
	echo "Usage: eyes <minutes>";
	exit 1;
fi

MINUTES=$1;

WINDOW_ID=$(xdotool getactivewindow);

center_text() {
	local text="$1"
	local termiinal_width=$(tput cols)
	local text_width=${#text}
	local padding=$(( ( termiinal_width - text_width ) / 2 ))

	if [ $padding -gt 0 ]; then
		printf "%${padding}s%s\n" "" "$text"
	else
		echo "$text"
	fi
}

while true; do
	echo "Timer started for $MINUTES minute(s)."

	SECONDS_LEFT=$((MINUTES * 60));

	while [ $SECONDS_LEFT -gt 0 ]; do
		M=$((SECONDS_LEFT / 60));
		S=$((SECONDS_LEFT % 60));

		TIME_STRING=$(printf "\r%02d:%02d " "$M" "$S");

		LINES=$(tput lines);
		V_CENTER=$(( (LINES - 7) / 2 ));
		
		tput cup $V_CENTER 0
		clear;

		center_text "TIME REMAINING:"

		FIG_OUT=$(figlet -f slant "$TIME_STRING")
		while IFS= read -r line; do
			center_text "$line"
		done <<< "$FIG_OUT"

		sleep 1;
		((SECONDS_LEFT--));
	done
	

	xdotool windowactivate --sync "$WINDOW_ID"
	xdotool windowraise "$WINDOW_ID"
	xdotool windowmap "$WINDOW_ID"

	clear

	choice=""

	COUNTER=0;

	while [ -z "$choice" ]; do

		SE=$((COUNTER % 60))
		MI=$((COUNTER / 60))
		clear
		COUNT_STRING=$(printf "\r%02d:%02d " "$MI" "$SE")

		
		echo "========="
		echo "$COUNT_STRING"
		echo "========="

		echo "1) Restart"
		echo "2) Exit"

		sleep 1;
		((COUNTER++))

		read -t 0.5 -n 1 input;

		if [ ! -z "$input" ]; then
			choice=$input

			case $choice in
				1) clear; choice=""; continue;;
				2) clear; exit 0;;
				*) choice=""; clear; echo "?";
			esac
		fi
	done
done
	
