#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e

sudo apt-get update

sudo apt -y install software-properties-common

echo "Starting PHP 8.4 installation..."

# Update system and install prerequisites
echo "Updating system packages..."
sudo apt-get update
sudo apt-get install -y ca-certificates apt-transport-https software-properties-common lsb-release curl

# Add Ondřej Surý's PHP PPA (The standard for PHP on Ubuntu/Debian)
echo "Adding PHP repository..."
sudo add-apt-repository ppa:ondrej/php
sudo apt-get update


# Install PHP 8.4 Core
echo "Installing PHP 8.4 core..."
sudo apt install -y php8.4 php8.4-cli php8.4-fpm php8.4-common

# Install Requested Extensions

echo "Installing PHP 8.4 extensions..."
sudo apt-get install -y \
    php8.4-mysql \
    php8.4-zip \
    php8.4-gd \
    php8.4-intl \
    php8.4-bcmath \
    php8.4-opcache \
    php8.4-redis \
    php8.4-imagick \
    php8.4-xml \
    php8.4-curl \
    php8.4-mbstring

# Verify Installation
echo "--------------------------------------------------"
echo "Installation complete."
echo "PHP Version:"
php -v
echo "--------------------------------------------------"
echo "Loaded Modules:"
php -m | grep -E 'pdo_mysql|mysqli|zip|gd|intl|bcmath|soap|opcache|exif|redis|imagick'

# Install composer

php -r "copy('https://getcomposer.org/installer', '/tmp/composer-setup.php');"
php -r "if (hash_file('sha384', '/tmp/composer-setup.php') === 'c8b085408188070d5f52bcfe4ecfbee5f727afa458b2573b8eaaf77b3419b0bf2768dc67c86944da1544f06fa544fd47') { echo 'Installer verified'.PHP_EOL; } else { echo 'Installer corrupt'.PHP_EOL; unlink('composer-setup.php'); exit(1); }"
php /tmp/composer-setup.php
php -r "unlink('/tmp/composer-setup.php');"

# Move composer to global path
sudo mv /tmp/composer.phar /usr/local/bin/composer
